CREATE DATABASE IF NOT EXISTS Compañia_aerea;
USE Compañia_aerea;

--T_AEROPLANO
CREATE TABLE T_AEROPLANO(
Matricula VARCHAR(10) NOT NULL PRIMARY KEY,
Capacidad TINYINT NOT NULL,
Fabricante VARCHAR(50) NOT NULL,
Modelo VARCHAR(50) NOT NULL,
Autonomia INT NOT NULL,
CONSTRAINT CK_CAPACIDAD 
CHECK (Capacidad<450),
CONSTRAINT CK_AUTONOMIA
CHECK (Autonomia<=48)
);

--T_TRABAJADOR 
CREATE TABLE T_TRABAJADOR(
ID CHAR(5) NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellido1 VARCHAR(50) NOT NULL,
Apellido2 VARCHAR(50) NULL,
Codigo_personal CHAR(5) NOT NULL,
CONSTRAINT FK_TRABAJADOR_CATEGORIA
FOREIGN KEY(Codigo_personal) REFERENCES T_CATEGORIA_PROFESIONAL(Codigo)
);
	
--T_CATEGORIA_PROFESIONAL
CREATE TABLE T_CATEGORIA_PROFESIONAL(
Codigo CHAR(5) NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);

--T_VUELO
CREATE TABLE T_VUELO(
ID CHAR(5) NOT NULL PRIMARY KEY,
Aeropuerto_Origen VARCHAR(50) NOT NULL,
Aeropuerto_Destino VARCHAR(50) NOT NULL,
Fechas DATE NOT NULL,
Matricula_Avion VARCHAR(10) NOT NULL,
CONSTRAINT FK_VUELO_AEROPLANO 
FOREIGN KEY (Matricula_Avion) REFERENCES T_AEROPLANO(Matricula)
);

--T_TRABAJADOR_FORMAR_VUELO
CREATE TABLE T_TRABAJADOR_FORMAR_VUELO(
ID_Vuelo CHAR(5) NOT NULL,
ID_Trabajador CHAR(5) NOT NULL,
PRIMARY KEY(ID_Vuelo,ID_Trabajador),
CONSTRAINT FK_TRABAJADOR_FORMAR_VUELO_VUELO
FOREIGN KEY(ID_Vuelo) REFERENCES T_VUELO(ID),
CONSTRAINT FK_TRABAJADOR_FORMAR_VUELO_TRABAJADOR
FOREIGN KEY(ID_Trabajador) REFERENCES T_TRABAJADOR(ID)
);

--T_LISTA_PASAJEROS
CREATE TABLE T_LISTA_PASAJEROS(
DNI CHAR(9) NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL
);

--T_VUELO_ALMACENAR_LISTA_PASAJEROS
CREATE TABLE T_VUELO_ALMACENAR_LISTA_PASAJEROS(
ID_Vuelo CHAR(5) NOT NULL,
DNI_Pasajeros CHAR(9) NOT NULL,
PRIMARY KEY (ID_Vuelo,DNI_Pasajeros),
Asiento CHAR(3) NOT NULL,
Clase CHAR(2) NOT NULL,
IdClase INT NOT NULL,
CONSTRAINT FK_VUELO_LISTA_PASAJEROS_CLASE
FOREIGN KEY (IdClase) REFERENCES T_IDENTIFICADOR-CLASE(IdClase),
CONSTRAINT FK_VUELO_ALMACENAR_LISTA_PASAJEROS_VUELO
FOREIGN KEY (ID_Vuelo) REFERENCES T_VUELO(ID),
CONSTRAINT FK_VUELO_ALMACENAR_LISTA_PASAJEROS_LISTA_PASAJEROS
FOREIGN KEY (DNI_Pasajeros) REFERENCES T_LISTA_PASAJEROS(DNI),
CONSTRAINT CK_Asiento
CHECK (Asiento>0)
);

--T_TELEFONO_TRABAJADOR
CREATE TABLE T_TELEFONO_TRABAJADOR(
ID_Trabajador CHAR(5) NOT NULL,
Telefono CHAR(9) NOT NULL,
PRIMARY KEY (ID_TRABAJADOR,Telefono),
CONSTRAINT FK_TELEFONO_TRABAJADOR_TRABAJADOR
FOREIGN KEY (ID_TRABAJADOR)  REFERENCES T_TRABAJADOR(ID)
);

--T_TELEFONO_CONTACTO
CREATE TABLE T_TELEFONO_CONTACTO(
DNI_Pasajeros CHAR(9) NOT NULL,
Telefono CHAR(9) NOT NULL,
PRIMARY KEY(DNI_Pasajeros,Telefono),
CONSTRAINT FK_TELEFONO_CONTACTO_LISTA_PASAJEROS 
FOREIGN KEY(DNI_Pasajeros) REFERENCES T_LISTA_PASAJEROS(DNI)
);

--T_IDENTIFICADOR_CLASE 
CREATE TABLE T_IDENTIFICADOR_CLASE(
IdClase INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(50) NOT NULL
);

//Jesus







